### ISSUE TITLE
Action zabbix.ack_event does't appear to acknowledge the event

### ISSUE THREAD

**Issue by jezkerwin** [StackStorm-Exchange/stackstorm-zabbix#31]
I'm trying to test the action `zabbix.ack_event` with an event to set the `Ack` flag to true.
I've configured the pack to talk to my Zabbix instance by running `st2 pack config zabbix`
When running the action from the command line, it appears to work, but nothing happens on the Zabbix instance
```
st2 run zabbix.ack_event eventid=1165 message="Testing 123" will_close=False
.
id: 5cc9a2e99a6fe02ac5aa39a2
status: succeeded
parameters:
  eventid: '1165'
  message: Testing 123
  will_close: false
result:
  exit_code: 0
  result:
    eventids:
    - 1165
  stderr: ''
  stdout: ''
```
![image](https://user-images.githubusercontent.com/1779665/57020000-626b2400-6c6b-11e9-9380-a9c2701be208.png)

Manually acknowledging the alert works.

**Comment by namachieli** [comment]
I will try testing this also.

What version of Zabbix are you running?

**Comment by jezkerwin** [comment]
Thanks.
Using the 4.2.1 Zabbix Appliance VM

**Comment by namachieli** [comment]
I just tested on `3.4.15` and its working. I did notice an issue with the parameter `will_close`. Its `type: boolean` but has an enum of `True, False`. IIRC Enum should only be used with `type: string`

Does it work if you leave `will_close` as `true` (default)?

**Comment by jezkerwin** [comment]
I'll have to confirm later on today, but from memory, I don't think setting `will_close` to `true` did work.
But I will confirm

**Comment by jezkerwin** [comment]
Confirmed that setting `will_close` to `True` will close a problem is the template allows manual closing.
Still doesn't `Acknowledge` the event though

**Comment by namachieli** [comment]
Looks like they changed how this api endpoint behaved in 4.0

4.0 - https://www.zabbix.com/documentation/4.0/manual/api/reference/event/acknowledge
3.4 - https://www.zabbix.com/documentation/3.4/manual/api/reference/event/acknowledge

I wonder if it has to do with the way the existing action use `type: boolean` for `will_close` when the api field is expecting `type: int`. It could be that when there were only the two options it still worked unintentionally, but when it was updated to have more than 2 options, a bool flag no longer works.

Can you try modifying your installed copy of `zabbix.ack_event` to

```
    will_close:
        type: int
        required: False
        default: 1
```

And try it again?

**Comment by jezkerwin** [comment]
I've editing my `ack_event.yaml` file to the following
```
---
name: ack_event
pack: zabbix
runner_type: python-script
description: Send acknowledgement message for an event to Zabbix and may close it
enabled: true
entry_point: event_action_runner.py
parameters:
    eventid:
        type: string
        required: True
    message:
        type: string
        required: True
    will_close:
        type: int
        required: True
        default: 1
    action:
        type: string
        immutable: true
        default: event.acknowledge
```
Still not setting the Ack 
I tried setting the `will_close` to `True` and it wasn't allowed because the alert I'm testing on, doesn't allow manual closing

**Comment by jezkerwin** [comment]
I was just playing around with using Postman and the API and the following POST request was able to acknowledge the problem.
```
curl -X POST \
  http://zabbix.domain.com/zabbix/api_jsonrpc.php \
  -H 'Content-Type: application/json' \
  -d '{
    "jsonrpc": "2.0",
    "method": "event.acknowledge",
    "params": {
        "eventids": "1271",
        "action": 2,
        "message": "Testing Using the API"
    },
    "id": 3,
    "auth": "<auth_token>"
}'
```
I'll see if I can put my limited Python/StackStorm knowledge to the test and see if I can troubleshoot the problem in code

**Comment by jezkerwin** [comment]
I think the problem might lie in the `actions.py` in the following function
```
    def reconstruct_args_for_ack_event(self, eventid, message, will_close):
        return {
            'eventids': eventid,
            'message': message,
            'action': 1 if will_close else 0,
        }
```

**Comment by jezkerwin** [comment]
Okay, I figured it out.

- Edited `will_close` option in `ack_event.yaml` to the following
```
will_close:
    type: integer
    required: True
    default: 1
```
- Also edited the `reconstruct_args_for_ack_event` in `actions.py` to the following
```
def reconstruct_args_for_ack_event(self, eventid, message, will_close):
       return {
           'eventids': eventid,
           'message': message,
           'action': will_close,
       }
```
Based on the API documentation [https://www.zabbix.com/documentation/4.2/manual/api/reference/event/acknowledge](url) It seems the option for action is a bitmask integer. I've tested it manually with 
`will_close=6` which will acknowledge the problem and add a message, based on `2 = acknowledge event` + `4 = add a message` 

I'm happy to submit a pull request with these changes if it's felt that this would be useful, I'm not sure if this would affect any older versions of Zabbix though.
